## Introduction to Numpy
NumPy (Numerical Python) is a core library for numerical computing in Python. It provides efficient data structures (primarily arrays) that allow for fast numerical computations. In data analysis, NumPy is widely used for performing mathematical operations on large datasets, and it forms the foundation for many other libraries, including Pandas.

### What is a NumPy Array?

A NumPy array (or ndarray) is a grid of values, all of the same type, indexed by a tuple of non-negative integers. Arrays can be one-dimensional (like a list), two-dimensional (like a table), or even higher dimensions. NumPy arrays are much faster and more memory-efficient than Python lists, making them ideal for large datasets.

In [1]:
import numpy as np

In [3]:
# creating an array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# create a 2d array
arr_2d = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])
print(arr_1d)
print(arr_2d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [6 7 8 9]]


## Array Operatins
NumPy allows you to perform element-wise operations on arrays, which makes it much more efficient than using loops.
#### Arethmetic operation

In [4]:
arr = np.array([1, 2, 3, 4])
# add 10 to each element 
arr_add = arr + 10
# mult every elemnt by 10

arr_mult = arr * 10

print(arr_add)
print(arr_mult)

[11 12 13 14]
[10 20 30 40]


## Mathematical Functions
NumPy includes various mathematical functions that operate element-wise on arrays:

In [5]:
# are root of each eement 
sqrt_arr = np.sqrt(arr)
# Natura logaryth fr each element
log_arr = np.log(arr)
print(sqrt_arr)
print(log_arr)

[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]


## Array Slicing and indexing

Like Python lists, you can slice and index NumPy arrays to access specific elements or subsets of the array.

In [8]:
arr = np.array([10, 20, 30, 40, 50])

# access a specific elemnt 
print(arr[0])
print(arr[1:3])
# for 2d arrays

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[0][2])
print(arr_2d[0, :])
print(arr_2d[:, 1])


10
[20 30]
3
[1 2 3]
[2 5]


## BroadCasting

NumPy allows arithmetic operations between arrays of different shapes through a process called broadcasting. This is highly useful when you want to perform operations on arrays of different dimensions.

In [9]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[20], [30], [40]])

# broadcasting addition

result = arr_1 + arr_2
print(result)

[[21 22 23]
 [31 32 33]
 [41 42 43]]


## Common Functions and Methods

NumPy provides a wide range of useful functions for performing common operations:

- `np.mean()`: Calculates the mean of the array.
- `np.median()`: Finds the median value.
- `np.sum()`: Computes the sum of all elements.
- `np.std()`: Calculates the standard deviation.

In [11]:
arr = np.array([1, 2, 3, 4, 5])

# Mean
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))

3.0
15
5


## Reshaping an Array

In [12]:
r_arr = np.array([1, 2, 3, 4, 5, 6])
print(r_arr)

[1 2 3 4 5 6]


In [15]:
# reshaping an array

arr_reshaped = r_arr.reshape(3, 2)
print(arr_reshaped)

[[1 2]
 [3 4]
 [5 6]]


## Generating Random Numbers

NumPy’s random module provides functions for generating random numbers, which are useful in simulations, random sampling, and machine learning.

In [17]:
# generate an array f randm numbers 0 and 1
randm_arr = np.random.rand(3, 3)
print(randm_arr)

[[0.492663   0.80557569 0.81709704]
 [0.76625567 0.00910487 0.70819527]
 [0.44864311 0.03276999 0.97335369]]


In [19]:
# generate random integers 
rand_int = np.random.randint(1, 10, size=(2, 3))
print(rand_int)

[[8 1 7]
 [8 3 7]]
